    PROJECT 1 - Explonatary Data Analysis 
       Dateset: MTA - Turnstile Weekly Dataset
       Period:  March 2021 - May 2021
       Coverage:

In [4]:
# 'Pandas' kütüphanesini 'pd' kısaltmasını kullanacak şekilde import ediyoruz (literatürde kullanılan kısaltma)
import pandas as pd
import numpy as np

In [5]:
# create a file list that will be used for appending
file_list=['http://web.mta.info/developers/data/nyct/turnstile/turnstile_220305.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220312.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220319.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220326.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220402.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220409.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220416.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220423.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220430.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220507.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220514.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220521.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220528.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220604.txt']
file_list

['http://web.mta.info/developers/data/nyct/turnstile/turnstile_220305.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220312.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220319.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220326.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220402.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220409.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220416.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220423.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220430.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220507.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220514.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220521.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220528.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220604.txt']

In [6]:
 # create a for loop to append weekly data files
main_df = pd.DataFrame(pd.read_csv(file_list[0]))
  
for i in range(1,len(file_list)):
    data = pd.read_csv(file_list[i])
    weekly_df= pd.DataFrame(data)
    main_df = pd.concat([main_df,weekly_df], ignore_index = True)
print(main_df)

           C/A  UNIT       SCP        STATION LINENAME DIVISION        DATE  \
0         A002  R051  02-00-00          59 ST  NQR456W      BMT  02/26/2022
1         A002  R051  02-00-00          59 ST  NQR456W      BMT  02/26/2022
2         A002  R051  02-00-00          59 ST  NQR456W      BMT  02/26/2022
3         A002  R051  02-00-00          59 ST  NQR456W      BMT  02/26/2022
4         A002  R051  02-00-00          59 ST  NQR456W      BMT  02/26/2022
...        ...   ...       ...            ...      ...      ...         ...
2951391  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/03/2022
2951392  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/03/2022
2951393  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/03/2022
2951394  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/03/2022
2951395  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/03/2022

             TIME     DESC  ENTRIES  \
0        03:00:00  REGULAR  7689737
1        07:00:00  REGULAR  7689741
2        11:00:00  REGULAR  7689758
3        15:00:00  REGULAR  7689791
4        19:00:00  REGULAR  7689858
...           ...      ...      ...
2951391  05:00:00  REGULAR        0
2951392  09:00:00  REGULAR        0
2951393  13:00:00  REGULAR        0
2951394  17:00:00  REGULAR        0
2951395  21:00:00  REGULAR        0

         EXITS
0                                                  2671257
1                                                  2671278
2                                                  2671380
3                                                  2671465
4                                                  2671530
...                                                    ...
2951391                                                433
2951392                                                433
2951393                                                433
2951394                                                435
2951395                                                435

[2951396 rows x 11 columns]

In [7]:
# check for indexes
main_df.tail(40)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
2951356,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/28/2022,09:00:00,REGULAR,0,389
2951357,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/28/2022,13:00:00,REGULAR,0,390
2951358,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/28/2022,17:00:00,REGULAR,0,391
2951359,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/28/2022,21:00:00,REGULAR,0,395
2951360,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/29/2022,01:00:00,REGULAR,0,395
2951361,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/29/2022,05:00:00,REGULAR,0,395
2951362,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/29/2022,09:00:00,REGULAR,0,395
2951363,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/29/2022,13:00:00,REGULAR,0,397
2951364,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/29/2022,17:00:00,REGULAR,0,404
2951365,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/29/2022,21:00:00,REGULAR,0,405
2951366,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/30/2022,01:00:00,REGULAR,0,405
2951367,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/30/2022,05:00:00,REGULAR,0,405
2951368,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/30/2022,09:00:00,REGULAR,0,407
2951369,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/30/2022,13:00:00,REGULAR,0,408
2951370,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/30/2022,17:00:00,REGULAR,0,414
2951371,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/30/2022,21:00:00,REGULAR,0,423
2951372,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/31/2022,01:00:00,REGULAR,0,425
2951373,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/31/2022,05:00:00,REGULAR,0,425
2951374,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/31/2022,09:00:00,REGULAR,0,426
2951375,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/31/2022,13:00:00,REGULAR,0,426
2951376,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/31/2022,17:00:00,REGULAR,0,426
2951377,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/31/2022,21:00:00,REGULAR,0,426
2951378,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/01/2022,01:00:00,REGULAR,0,426
2951379,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/01/2022,05:00:00,REGULAR,0,426
2951380,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/01/2022,09:00:00,REGULAR,0,427
2951381,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/01/2022,13:00:00,REGULAR,0,428
2951382,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/01/2022,17:00:00,REGULAR,0,429
2951383,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/01/2022,21:00:00,REGULAR,0,430
2951384,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/02/2022,01:00:00,REGULAR,0,430
2951385,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/02/2022,05:00:00,REGULAR,0,430
2951386,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/02/2022,09:00:00,REGULAR,0,430
2951387,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/02/2022,13:00:00,REGULAR,0,430
2951388,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/02/2022,17:00:00,REGULAR,0,432
2951389,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/02/2022,21:00:00,REGULAR,0,432
2951390,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/03/2022,01:00:00,REGULAR,0,433
2951391,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/03/2022,05:00:00,REGULAR,0,433
2951392,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/03/2022,09:00:00,REGULAR,0,433
2951393,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/03/2022,13:00:00,REGULAR,0,433
2951394,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/03/2022,17:00:00,REGULAR,0,435
2951395,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,06/03/2022,21:00:00,REGULAR,0,435

In [8]:
main_df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2022,03:00:00,REGULAR,7689737,2671257
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2022,07:00:00,REGULAR,7689741,2671278
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2022,11:00:00,REGULAR,7689758,2671380
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2022,15:00:00,REGULAR,7689791,2671465
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2022,19:00:00,REGULAR,7689858,2671530

In [9]:
# check variable types and null values
main_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2951396 entries, 0 to 2951395
Data columns (total 11 columns):
 #   Column                                                                Non-Null Count    Dtype
---  ------                                                                --------------    -----
 0   C/A                                                                   2951396 non-null  object
 1   UNIT                                                                  2951396 non-null  object
 2   SCP                                                                   2951396 non-null  object
 3   STATION                                                               2951396 non-null  object
 4   LINENAME                                                              2951396 non-null  object
 5   DIVISION                                                              2951396 non-null  object
 6   DATE                                                                  2951396 non-null  object
 7   TIME                                                                  2951396 non-null  object
 8   DESC                                                                  2951396 non-null  object
 9   ENTRIES                                                               2951396 non-null  int64
 10  EXITS                                                                 2951396 non-null  int64
dtypes: int64(2), object(9)
memory usage: 247.7+ MB

In [10]:
# check for column names
main_df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES',
       'EXITS                                                               '],
      dtype='object')

In [11]:
# rename columns and keep the changes
main_df.rename(columns={'C/A': 'control_area','UNIT':'station_id','SCP':'device_position', 'STATION': 'station', 'LINENAME':'line','DIVISION':'division','DATE':'date','TIME':'time','DESC':'interval','ENTRIES':'entry','EXITS                                                               ':'exit'},inplace=True)

In [12]:
main_df.columns

Index(['control_area', 'station_id', 'device_position', 'station', 'line',
       'division', 'date', 'time', 'interval', 'entry', 'exit'],
      dtype='object')

In [13]:
main_df.exit

0          2671257
1          2671278
2          2671380
3          2671465
4          2671530
            ...
2951391        433
2951392        433
2951393        433
2951394        435
2951395        435
Name: exit, Length: 2951396, dtype: int64

In [14]:
# format numeric entries
pd.options.display.float_format = '{:,.1f}'.format

In [15]:
main_df.describe()

                entry            exit
count     2,951,396.0     2,951,396.0
mean     42,937,462.0    34,554,979.9
std     223,558,595.2   197,082,673.0
min               0.0             0.0
25%         249,067.0       132,792.8
50%       1,354,766.0       886,175.5
75%       5,965,626.8     3,975,187.0
max   2,147,319,334.0 2,122,443,345.0

In [16]:
# import datetime to work with time and date
import numpy as np
from datetime import datetime

In [17]:
main_df['date'] = pd.to_datetime(main_df['date'])

In [18]:
# check the data type of date
main_df.date.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2951396 entries, 0 to 2951395
Series name: date
Non-Null Count    Dtype
--------------    -----
2951396 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 22.5 MB

In [19]:
main_df.date.head(40)

0    2022-02-26
1    2022-02-26
2    2022-02-26
3    2022-02-26
4    2022-02-26
5    2022-02-26
6    2022-02-27
7    2022-02-27
8    2022-02-27
9    2022-02-27
10   2022-02-27
11   2022-02-27
12   2022-02-28
13   2022-02-28
14   2022-02-28
15   2022-02-28
16   2022-02-28
17   2022-02-28
18   2022-03-01
19   2022-03-01
20   2022-03-01
21   2022-03-01
22   2022-03-01
23   2022-03-01
24   2022-03-02
25   2022-03-02
26   2022-03-02
27   2022-03-02
28   2022-03-02
29   2022-03-02
30   2022-03-03
31   2022-03-03
32   2022-03-03
33   2022-03-03
34   2022-03-03
35   2022-03-03
36   2022-03-04
37   2022-03-04
38   2022-03-04
39   2022-03-04
Name: date, dtype: datetime64[ns]

In [20]:
main_df['time_clone'] = pd.to_datetime(main_df['time'])

In [21]:
main_df['hour'] = main_df.time_clone.dt.hour

In [22]:
 main_df.drop(['time_clone'], axis=1)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,hour
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,3
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,11
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,15
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,19
...,...,...,...,...,...,...,...,...,...,...,...,...
2951391,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,05:00:00,REGULAR,0,433,5
2951392,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,09:00:00,REGULAR,0,433,9
2951393,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,13:00:00,REGULAR,0,433,13
2951394,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,17:00:00,REGULAR,0,435,17
2951395,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,21:00:00,REGULAR,0,435,21

In [23]:
main_df.head(50)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-25 03:00:00,3
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-25 07:00:00,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-25 11:00:00,11
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-25 15:00:00,15
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-25 19:00:00,19
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,7689890,2671568,2022-12-25 23:00:00,23
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,7689903,2671580,2022-12-25 03:00:00,3
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,7689908,2671583,2022-12-25 07:00:00,7
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,11:00:00,REGULAR,7689924,2671637,2022-12-25 11:00:00,11
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,15:00:00,REGULAR,7689970,2671692,2022-12-25 15:00:00,15
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,19:00:00,REGULAR,7690010,2671742,2022-12-25 19:00:00,19
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,23:00:00,REGULAR,7690046,2671763,2022-12-25 23:00:00,23
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,03:00:00,REGULAR,7690057,2671766,2022-12-25 03:00:00,3
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,07:00:00,REGULAR,7690058,2671821,2022-12-25 07:00:00,7
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,11:00:00,REGULAR,7690091,2672117,2022-12-25 11:00:00,11
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,15:00:00,REGULAR,7690159,2672193,2022-12-25 15:00:00,15
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,19:00:00,REGULAR,7690336,2672264,2022-12-25 19:00:00,19
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,23:00:00,REGULAR,7690377,2672288,2022-12-25 23:00:00,23
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,03:00:00,REGULAR,7690386,2672291,2022-12-25 03:00:00,3
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,07:00:00,REGULAR,7690388,2672343,2022-12-25 07:00:00,7
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,11:00:00,REGULAR,7690420,2672647,2022-12-25 11:00:00,11
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,15:00:00,REGULAR,7690497,2672714,2022-12-25 15:00:00,15
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,19:00:00,REGULAR,7690681,2672803,2022-12-25 19:00:00,19
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,23:00:00,REGULAR,7690719,2672824,2022-12-25 23:00:00,23
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,03:00:00,REGULAR,7690725,2672830,2022-12-25 03:00:00,3
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,07:00:00,REGULAR,7690730,2672886,2022-12-25 07:00:00,7
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,11:00:00,REGULAR,7690764,2673196,2022-12-25 11:00:00,11
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,15:00:00,REGULAR,7690834,2673275,2022-12-25 15:00:00,15
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,19:00:00,REGULAR,7691026,2673349,2022-12-25 19:00:00,19
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,23:00:00,REGULAR,7691071,2673379,2022-12-25 23:00:00,23
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,03:00:00,REGULAR,7691078,2673386,2022-12-25 03:00:00,3
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,07:00:00,REGULAR,7691083,2673435,2022-12-25 07:00:00,7
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,11:00:00,REGULAR,7691111,2673707,2022-12-25 11:00:00,11
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,15:00:00,REGULAR,7691171,2673791,2022-12-25 15:00:00,15
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,19:00:00,REGULAR,7691319,2673892,2022-12-25 19:00:00,19
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,23:00:00,REGULAR,7691363,2673919,2022-12-25 23:00:00,23
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,03:00:00,REGULAR,7691372,2673927,2022-12-25 03:00:00,3
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,07:00:00,REGULAR,7691374,2673965,2022-12-25 07:00:00,7
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,11:00:00,REGULAR,7691399,2674256,2022-12-25 11:00:00,11
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,15:00:00,REGULAR,7691470,2674324,2022-12-25 15:00:00,15
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,19:00:00,REGULAR,7691643,2674405,2022-12-25 19:00:00,19
41,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,23:00:00,REGULAR,7691692,2674436,2022-12-25 23:00:00,23
42,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,6803069,1576702,2022-12-25 03:00:00,3
43,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,6803071,1576712,2022-12-25 07:00:00,7
44,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,6803085,1576759,2022-12-25 11:00:00,11
45,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,6803131,1576797,2022-12-25 15:00:00,15
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,6803195,1576836,2022-12-25 19:00:00,19
47,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,6803246,1576854,2022-12-25 23:00:00,23
48,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,6803257,1576862,2022-12-25 03:00:00,3
49,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,6803257,1576870,2022-12-25 07:00:00,7

In [24]:
main_df["weekdays"] = main_df.date.dt.weekday

In [25]:
main_df.head()

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour,weekdays
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-25 03:00:00,3,5
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-25 07:00:00,7,5
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-25 11:00:00,11,5
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-25 15:00:00,15,5
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-25 19:00:00,19,5

In [26]:
main_df["week"] = main_df["date"].dt.isocalendar().week

In [27]:
main_df["day"] = main_df["date"].dt.day

In [28]:
# add a month variable to the dataset
main_df["month"] = main_df["date"].dt.month

In [29]:
main_df.head()

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour,weekdays,week,day,month
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-25 03:00:00,3,5,8,26,2
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-25 07:00:00,7,5,8,26,2
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-25 11:00:00,11,5,8,26,2
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-25 15:00:00,15,5,8,26,2
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-25 19:00:00,19,5,8,26,2

In [30]:
main_df.month.unique()

array([2, 3, 4, 5, 6], dtype=int64)

In [31]:
main_df.week.unique()

<IntegerArray>
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Length: 15, dtype: UInt32

In [32]:
main_df.day.unique()

array([26, 27, 28,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 29, 30, 31],
      dtype=int64)

In [33]:
main_df.weekdays.unique()

array([5, 6, 0, 1, 2, 3, 4], dtype=int64)

In [34]:
main_df.hour.unique()

array([ 3,  7, 11, 15, 19, 23,  1,  5,  9, 12, 13, 17, 21,  8,  0,  4, 16,
       20,  2,  6, 10, 14, 18, 22], dtype=int64)

In [36]:
main_df.interval.unique()

array(['REGULAR', 'RECOVR AUD'], dtype=object)

In [68]:
main_df.loc[main_df.interval == 'RECOVR AUD', ['interval','entry', 'exit', 'hour']]

           interval    entry      exit  hour
1978     RECOVR AUD  6290989  39503704    11
2020     RECOVR AUD    38583     89822    11
2062     RECOVR AUD  6589112   3436081    11
2104     RECOVR AUD  6284446   2775730    11
2146     RECOVR AUD     1573         0    11
...             ...      ...       ...   ...
2950910  RECOVR AUD   262799     65536    14
2950911  RECOVR AUD   262799     65536    18
2950956  RECOVR AUD      868         0    10
2950957  RECOVR AUD      871         0    14
2950958  RECOVR AUD      872         0    18

[13157 rows x 4 columns]

In [38]:
main_df['weekend'] = (main_df.weekdays == 5) |  (main_df.weekdays == 6)
main_df.head(40)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour,weekdays,week,day,month,weekend
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-25 03:00:00,3,5,8,26,2,True
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-25 07:00:00,7,5,8,26,2,True
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-25 11:00:00,11,5,8,26,2,True
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-25 15:00:00,15,5,8,26,2,True
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-25 19:00:00,19,5,8,26,2,True
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,7689890,2671568,2022-12-25 23:00:00,23,5,8,26,2,True
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,7689903,2671580,2022-12-25 03:00:00,3,6,8,27,2,True
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,7689908,2671583,2022-12-25 07:00:00,7,6,8,27,2,True
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,11:00:00,REGULAR,7689924,2671637,2022-12-25 11:00:00,11,6,8,27,2,True
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,15:00:00,REGULAR,7689970,2671692,2022-12-25 15:00:00,15,6,8,27,2,True
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,19:00:00,REGULAR,7690010,2671742,2022-12-25 19:00:00,19,6,8,27,2,True
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,23:00:00,REGULAR,7690046,2671763,2022-12-25 23:00:00,23,6,8,27,2,True
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,03:00:00,REGULAR,7690057,2671766,2022-12-25 03:00:00,3,0,9,28,2,False
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,07:00:00,REGULAR,7690058,2671821,2022-12-25 07:00:00,7,0,9,28,2,False
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,11:00:00,REGULAR,7690091,2672117,2022-12-25 11:00:00,11,0,9,28,2,False
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,15:00:00,REGULAR,7690159,2672193,2022-12-25 15:00:00,15,0,9,28,2,False
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,19:00:00,REGULAR,7690336,2672264,2022-12-25 19:00:00,19,0,9,28,2,False
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,23:00:00,REGULAR,7690377,2672288,2022-12-25 23:00:00,23,0,9,28,2,False
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,03:00:00,REGULAR,7690386,2672291,2022-12-25 03:00:00,3,1,9,1,3,False
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,07:00:00,REGULAR,7690388,2672343,2022-12-25 07:00:00,7,1,9,1,3,False
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,11:00:00,REGULAR,7690420,2672647,2022-12-25 11:00:00,11,1,9,1,3,False
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,15:00:00,REGULAR,7690497,2672714,2022-12-25 15:00:00,15,1,9,1,3,False
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,19:00:00,REGULAR,7690681,2672803,2022-12-25 19:00:00,19,1,9,1,3,False
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,23:00:00,REGULAR,7690719,2672824,2022-12-25 23:00:00,23,1,9,1,3,False
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,03:00:00,REGULAR,7690725,2672830,2022-12-25 03:00:00,3,2,9,2,3,False
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,07:00:00,REGULAR,7690730,2672886,2022-12-25 07:00:00,7,2,9,2,3,False
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,11:00:00,REGULAR,7690764,2673196,2022-12-25 11:00:00,11,2,9,2,3,False
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,15:00:00,REGULAR,7690834,2673275,2022-12-25 15:00:00,15,2,9,2,3,False
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,19:00:00,REGULAR,7691026,2673349,2022-12-25 19:00:00,19,2,9,2,3,False
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,23:00:00,REGULAR,7691071,2673379,2022-12-25 23:00:00,23,2,9,2,3,False
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,03:00:00,REGULAR,7691078,2673386,2022-12-25 03:00:00,3,3,9,3,3,False
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,07:00:00,REGULAR,7691083,2673435,2022-12-25 07:00:00,7,3,9,3,3,False
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,11:00:00,REGULAR,7691111,2673707,2022-12-25 11:00:00,11,3,9,3,3,False
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,15:00:00,REGULAR,7691171,2673791,2022-12-25 15:00:00,15,3,9,3,3,False
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,19:00:00,REGULAR,7691319,2673892,2022-12-25 19:00:00,19,3,9,3,3,False
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,23:00:00,REGULAR,7691363,2673919,2022-12-25 23:00:00,23,3,9,3,3,False
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,03:00:00,REGULAR,7691372,2673927,2022-12-25 03:00:00,3,4,9,4,3,False
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,07:00:00,REGULAR,7691374,2673965,2022-12-25 07:00:00,7,4,9,4,3,False
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,11:00:00,REGULAR,7691399,2674256,2022-12-25 11:00:00,11,4,9,4,3,False
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,15:00:00,REGULAR,7691470,2674324,2022-12-25 15:00:00,15,4,9,4,3,False

In [39]:
# main_df.drop(['weekends'], axis=1)

In [40]:
min_max_df=main_df.groupby(['station', 'station_id', 'control_area','device_position','line','division','date']).agg(hour_min=('hour','min'),hour_max=('hour','max'), entry_min=('entry','min'), entry_max=('entry', 'max'), exit_min=('exit', 'min'), exit_max=('exit','max')).reset_index()

In [41]:
min_max_df.head(40)

,station,station_id,control_area,device_position,line,division,date,hour_min,hour_max,entry_min,entry_max,exit_min,exit_max
0,1 AV,R248,H007,00-00-00,L,BMT,2022-02-26,3,23,15727954,15727954,18465387,18465388
1,1 AV,R248,H007,00-00-00,L,BMT,2022-02-27,3,23,15727954,15727954,18465388,18465393
2,1 AV,R248,H007,00-00-00,L,BMT,2022-02-28,3,23,15727954,15728695,18465393,18467923
3,1 AV,R248,H007,00-00-00,L,BMT,2022-03-01,3,23,15728706,15729440,18467996,18470794
4,1 AV,R248,H007,00-00-00,L,BMT,2022-03-02,3,23,15729463,15730194,18470883,18473712
5,1 AV,R248,H007,00-00-00,L,BMT,2022-03-03,3,23,15730215,15731024,18473795,18476653
6,1 AV,R248,H007,00-00-00,L,BMT,2022-03-04,3,23,15731042,15731762,18476745,18479791
7,1 AV,R248,H007,00-00-00,L,BMT,2022-03-05,3,23,15731799,15732150,18479989,18482026
8,1 AV,R248,H007,00-00-00,L,BMT,2022-03-06,3,23,15732178,15732429,18482244,18483816
9,1 AV,R248,H007,00-00-00,L,BMT,2022-03-07,3,23,15732438,15733100,18483881,18486696
10,1 AV,R248,H007,00-00-00,L,BMT,2022-03-08,3,23,15733108,15733841,18486757,18489587
11,1 AV,R248,H007,00-00-00,L,BMT,2022-03-09,3,23,15733854,15734683,18489656,18492356
12,1 AV,R248,H007,00-00-00,L,BMT,2022-03-10,3,23,15734702,15735497,18492434,18495343
13,1 AV,R248,H007,00-00-00,L,BMT,2022-03-11,3,23,15735522,15736315,18495427,18498366
14,1 AV,R248,H007,00-00-00,L,BMT,2022-03-12,3,23,15736354,15736694,18498584,18500387
15,1 AV,R248,H007,00-00-00,L,BMT,2022-03-13,4,20,15736717,15736935,18500550,18502091
16,1 AV,R248,H007,00-00-00,L,BMT,2022-03-14,0,20,15736999,15737660,18502330,18504824
17,1 AV,R248,H007,00-00-00,L,BMT,2022-03-15,0,20,15737730,15738377,18505037,18507629
18,1 AV,R248,H007,00-00-00,L,BMT,2022-03-16,0,20,15738456,15739199,18507946,18510646
19,1 AV,R248,H007,00-00-00,L,BMT,2022-03-17,0,20,15739279,15739976,18510909,18513733
20,1 AV,R248,H007,00-00-00,L,BMT,2022-03-18,0,20,15740078,15740715,18514088,18516696
21,1 AV,R248,H007,00-00-00,L,BMT,2022-03-19,0,20,15740820,15741083,18517169,18519225
22,1 AV,R248,H007,00-00-00,L,BMT,2022-03-20,0,20,15741173,15741437,18519643,18521289
23,1 AV,R248,H007,00-00-00,L,BMT,2022-03-21,0,20,15741486,15742071,18521532,18524075
24,1 AV,R248,H007,00-00-00,L,BMT,2022-03-22,0,20,15742137,15742833,18524314,18526947
25,1 AV,R248,H007,00-00-00,L,BMT,2022-03-23,0,20,15742902,15743508,18527215,18529681
26,1 AV,R248,H007,00-00-00,L,BMT,2022-03-24,0,20,15743584,15744289,18529945,18532431
27,1 AV,R248,H007,00-00-00,L,BMT,2022-03-25,0,20,15744384,15745073,18532719,18535553
28,1 AV,R248,H007,00-00-00,L,BMT,2022-03-26,0,20,15745180,15745511,18536010,18537839
29,1 AV,R248,H007,00-00-00,L,BMT,2022-03-27,0,20,15745641,15745909,18538247,18539787
30,1 AV,R248,H007,00-00-00,L,BMT,2022-03-28,0,20,15745985,15746662,18539987,18542438
31,1 AV,R248,H007,00-00-00,L,BMT,2022-03-29,0,20,15746733,15747458,18542639,18545248
32,1 AV,R248,H007,00-00-00,L,BMT,2022-03-30,0,20,15747543,15748245,18545490,18548104
33,1 AV,R248,H007,00-00-00,L,BMT,2022-03-31,0,20,15748322,15748848,18548384,18551022
34,1 AV,R248,H007,00-00-00,L,BMT,2022-04-01,0,20,15748943,15749626,18551347,18553971
35,1 AV,R248,H007,00-00-00,L,BMT,2022-04-02,0,20,15749731,15750042,18554406,18556457
36,1 AV,R248,H007,00-00-00,L,BMT,2022-04-03,0,20,15750131,15750361,18556862,18558445
37,1 AV,R248,H007,00-00-00,L,BMT,2022-04-04,0,20,15750420,15751046,18558680,18561415
38,1 AV,R248,H007,00-00-00,L,BMT,2022-04-05,0,20,15751126,15751810,18561680,18564305
39,1 AV,R248,H007,00-00-00,L,BMT,2022-04-06,0,20,15751899,15752602,18564566,18567167

In [42]:
min_max_df.columns

Index(['station', 'station_id', 'control_area', 'device_position', 'line',
       'division', 'date', 'hour_min', 'hour_max', 'entry_min', 'entry_max',
       'exit_min', 'exit_max'],
      dtype='object')

In [43]:
merged_df=pd.merge(main_df,min_max_df, on=['station', 'station_id', 'control_area','device_position','line','division','date'], how='left')

In [44]:
merged_df.tail(50)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,...,week,day,month,weekend,hour_min,hour_max,entry_min,entry_max,exit_min,exit_max
2951346,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-02,17:00:00,REGULAR,333423,...,22,2,6,False,1,21,333353,333429,0,0
2951347,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-02,21:00:00,REGULAR,333429,...,22,2,6,False,1,21,333353,333429,0,0
2951348,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,01:00:00,REGULAR,333432,...,22,3,6,False,1,21,333432,333517,0,0
2951349,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,05:00:00,REGULAR,333432,...,22,3,6,False,1,21,333432,333517,0,0
2951350,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,09:00:00,REGULAR,333453,...,22,3,6,False,1,21,333432,333517,0,0
2951351,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,13:00:00,REGULAR,333475,...,22,3,6,False,1,21,333432,333517,0,0
2951352,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,17:00:00,REGULAR,333504,...,22,3,6,False,1,21,333432,333517,0,0
2951353,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,21:00:00,REGULAR,333517,...,22,3,6,False,1,21,333432,333517,0,0
2951354,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,01:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951355,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,05:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951356,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,09:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951357,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,13:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951358,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,17:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951359,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,21:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951360,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,01:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951361,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,05:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951362,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,09:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951363,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,13:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951364,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,17:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951365,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,21:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951366,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,01:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951367,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,05:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951368,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,09:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951369,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,13:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951370,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,17:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951371,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,21:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951372,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,01:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951373,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,05:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951374,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,09:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951375,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,13:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951376,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,17:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951377,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,21:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951378,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,01:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951379,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,05:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951380,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,09:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951381,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,13:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951382,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,17:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951383,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,21:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951384,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,01:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951385,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,05:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951386,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,09:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951387,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,13:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951388,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,17:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951389,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,21:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951390,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,01:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951391,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,05:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951392,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,09:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951393,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,13:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951394,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,17:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951395,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,21:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435

In [45]:
merged_df.columns

Index(['control_area', 'station_id', 'device_position', 'station', 'line',
       'division', 'date', 'time', 'interval', 'entry', 'exit', 'time_clone',
       'hour', 'weekdays', 'week', 'day', 'month', 'weekend', 'hour_min',
       'hour_max', 'entry_min', 'entry_max', 'exit_min', 'exit_max'],
      dtype='object')

In [46]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2951396 entries, 0 to 2951395
Data columns (total 24 columns):
 #   Column           Dtype
---  ------           -----
 0   control_area     object
 1   station_id       object
 2   device_position  object
 3   station          object
 4   line             object
 5   division         object
 6   date             datetime64[ns]
 7   time             object
 8   interval         object
 9   entry            int64
 10  exit             int64
 11  time_clone       datetime64[ns]
 12  hour             int64
 13  weekdays         int64
 14  week             UInt32
 15  day              int64
 16  month            int64
 17  weekend          bool
 18  hour_min         int64
 19  hour_max         int64
 20  entry_min        int64
 21  entry_max        int64
 22  exit_min         int64
 23  exit_max         int64
dtypes: UInt32(1), bool(1), datetime64[ns](2), int64(12), object(8)
memory usage: 534.8+ MB