    PROJECT 1 - Explonatary Data Analysis 
       Dateset: MTA - Turnstile Weekly Dataset
       Period:  March 2021 - May 2021
       Coverage:

In [2]:
# 'Pandas' kütüphanesini 'pd' kısaltmasını kullanacak şekilde import ediyoruz (literatürde kullanılan kısaltma)
import pandas as pd
import numpy as np

In [3]:
# create a file list that will be used for appending
file_list=['http://web.mta.info/developers/data/nyct/turnstile/turnstile_220305.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220312.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220319.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220326.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220402.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220409.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220416.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220423.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220430.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220507.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220514.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220521.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220528.txt','http://web.mta.info/developers/data/nyct/turnstile/turnstile_220604.txt']
file_list

['http://web.mta.info/developers/data/nyct/turnstile/turnstile_220305.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220312.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220319.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220326.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220402.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220409.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220416.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220423.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220430.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220507.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220514.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220521.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220528.txt',
 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_220604.txt']

In [6]:
 # create a for loop to append weekly data files
main_df = pd.DataFrame(pd.read_csv(file_list[0]))
  
for i in range(1,len(file_list)):
    data = pd.read_csv(file_list[i])
    weekly_df= pd.DataFrame(data)
    main_df = pd.concat([main_df,weekly_df], ignore_index = True)
print(main_df)

ParserError: Error tokenizing data. C error: Expected 11 fields in line 98537, saw 16

In [ ]:
# check for indexes
main_df.tail(40)

In [ ]:
main_df.head()

In [1]:
# check variable types and null values
main_df.info(verbose=True, show_counts=True)

NameError: name 'main_df' is not defined

In [348]:
# check for column names
main_df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES',
       'EXITS                                                               '],
      dtype='object')

In [349]:
# rename columns and keep the changes
main_df.rename(columns={'C/A': 'control_area','UNIT':'station_id','SCP':'device_position', 'STATION': 'station', 'LINENAME':'line','DIVISION':'division','DATE':'date','TIME':'time','DESC':'interval','ENTRIES':'entry','EXITS                                                               ':'exit'},inplace=True)

In [350]:
main_df.columns

Index(['control_area', 'station_id', 'device_position', 'station', 'line',
       'division', 'date', 'time', 'interval', 'entry', 'exit'],
      dtype='object')

In [351]:
main_df.exit

0          2671257
1          2671278
2          2671380
3          2671465
4          2671530
            ...
2951391        433
2951392        433
2951393        433
2951394        435
2951395        435
Name: exit, Length: 2951396, dtype: int64

In [352]:
# format numeric entries
pd.options.display.float_format = '{:,.1f}'.format

In [353]:
main_df.describe()

                entry            exit
count     2,951,396.0     2,951,396.0
mean     42,937,462.0    34,554,979.9
std     223,558,595.2   197,082,673.0
min               0.0             0.0
25%         249,067.0       132,792.8
50%       1,354,766.0       886,175.5
75%       5,965,626.8     3,975,187.0
max   2,147,319,334.0 2,122,443,345.0

In [354]:
# import datetime to work with time and date
import numpy as np
from datetime import datetime

In [355]:
main_df['date'] = pd.to_datetime(main_df['date'])

In [356]:
# check the data type of date
main_df.date.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2951396 entries, 0 to 2951395
Series name: date
Non-Null Count    Dtype
--------------    -----
2951396 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 22.5 MB

In [357]:
main_df.date.head(40)

0    2022-02-26
1    2022-02-26
2    2022-02-26
3    2022-02-26
4    2022-02-26
5    2022-02-26
6    2022-02-27
7    2022-02-27
8    2022-02-27
9    2022-02-27
10   2022-02-27
11   2022-02-27
12   2022-02-28
13   2022-02-28
14   2022-02-28
15   2022-02-28
16   2022-02-28
17   2022-02-28
18   2022-03-01
19   2022-03-01
20   2022-03-01
21   2022-03-01
22   2022-03-01
23   2022-03-01
24   2022-03-02
25   2022-03-02
26   2022-03-02
27   2022-03-02
28   2022-03-02
29   2022-03-02
30   2022-03-03
31   2022-03-03
32   2022-03-03
33   2022-03-03
34   2022-03-03
35   2022-03-03
36   2022-03-04
37   2022-03-04
38   2022-03-04
39   2022-03-04
Name: date, dtype: datetime64[ns]

In [358]:
main_df['time_clone'] = pd.to_datetime(main_df['time'])

In [359]:
main_df['hour'] = main_df.time_clone.dt.hour

In [360]:
 main_df.drop(['time_clone'], axis=1)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,hour
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,3
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,11
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,15
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,19
...,...,...,...,...,...,...,...,...,...,...,...,...
2951391,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,05:00:00,REGULAR,0,433,5
2951392,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,09:00:00,REGULAR,0,433,9
2951393,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,13:00:00,REGULAR,0,433,13
2951394,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,17:00:00,REGULAR,0,435,17
2951395,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,21:00:00,REGULAR,0,435,21

In [361]:
main_df.head(50)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-23 03:00:00,3
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-23 07:00:00,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-23 11:00:00,11
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-23 15:00:00,15
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-23 19:00:00,19
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,7689890,2671568,2022-12-23 23:00:00,23
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,7689903,2671580,2022-12-23 03:00:00,3
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,7689908,2671583,2022-12-23 07:00:00,7
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,11:00:00,REGULAR,7689924,2671637,2022-12-23 11:00:00,11
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,15:00:00,REGULAR,7689970,2671692,2022-12-23 15:00:00,15
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,19:00:00,REGULAR,7690010,2671742,2022-12-23 19:00:00,19
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,23:00:00,REGULAR,7690046,2671763,2022-12-23 23:00:00,23
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,03:00:00,REGULAR,7690057,2671766,2022-12-23 03:00:00,3
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,07:00:00,REGULAR,7690058,2671821,2022-12-23 07:00:00,7
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,11:00:00,REGULAR,7690091,2672117,2022-12-23 11:00:00,11
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,15:00:00,REGULAR,7690159,2672193,2022-12-23 15:00:00,15
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,19:00:00,REGULAR,7690336,2672264,2022-12-23 19:00:00,19
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,23:00:00,REGULAR,7690377,2672288,2022-12-23 23:00:00,23
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,03:00:00,REGULAR,7690386,2672291,2022-12-23 03:00:00,3
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,07:00:00,REGULAR,7690388,2672343,2022-12-23 07:00:00,7
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,11:00:00,REGULAR,7690420,2672647,2022-12-23 11:00:00,11
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,15:00:00,REGULAR,7690497,2672714,2022-12-23 15:00:00,15
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,19:00:00,REGULAR,7690681,2672803,2022-12-23 19:00:00,19
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,23:00:00,REGULAR,7690719,2672824,2022-12-23 23:00:00,23
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,03:00:00,REGULAR,7690725,2672830,2022-12-23 03:00:00,3
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,07:00:00,REGULAR,7690730,2672886,2022-12-23 07:00:00,7
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,11:00:00,REGULAR,7690764,2673196,2022-12-23 11:00:00,11
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,15:00:00,REGULAR,7690834,2673275,2022-12-23 15:00:00,15
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,19:00:00,REGULAR,7691026,2673349,2022-12-23 19:00:00,19
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,23:00:00,REGULAR,7691071,2673379,2022-12-23 23:00:00,23
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,03:00:00,REGULAR,7691078,2673386,2022-12-23 03:00:00,3
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,07:00:00,REGULAR,7691083,2673435,2022-12-23 07:00:00,7
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,11:00:00,REGULAR,7691111,2673707,2022-12-23 11:00:00,11
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,15:00:00,REGULAR,7691171,2673791,2022-12-23 15:00:00,15
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,19:00:00,REGULAR,7691319,2673892,2022-12-23 19:00:00,19
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,23:00:00,REGULAR,7691363,2673919,2022-12-23 23:00:00,23
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,03:00:00,REGULAR,7691372,2673927,2022-12-23 03:00:00,3
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,07:00:00,REGULAR,7691374,2673965,2022-12-23 07:00:00,7
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,11:00:00,REGULAR,7691399,2674256,2022-12-23 11:00:00,11
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,15:00:00,REGULAR,7691470,2674324,2022-12-23 15:00:00,15
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,19:00:00,REGULAR,7691643,2674405,2022-12-23 19:00:00,19
41,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,23:00:00,REGULAR,7691692,2674436,2022-12-23 23:00:00,23
42,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,6803069,1576702,2022-12-23 03:00:00,3
43,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,6803071,1576712,2022-12-23 07:00:00,7
44,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,6803085,1576759,2022-12-23 11:00:00,11
45,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,6803131,1576797,2022-12-23 15:00:00,15
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,6803195,1576836,2022-12-23 19:00:00,19
47,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,6803246,1576854,2022-12-23 23:00:00,23
48,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,6803257,1576862,2022-12-23 03:00:00,3
49,A002,R051,02-00-01,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,6803257,1576870,2022-12-23 07:00:00,7

In [362]:
main_df["weekdays"] = main_df.date.dt.weekday

In [363]:
main_df.head()

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour,weekdays
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-23 03:00:00,3,5
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-23 07:00:00,7,5
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-23 11:00:00,11,5
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-23 15:00:00,15,5
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-23 19:00:00,19,5

In [364]:
main_df["week"] = main_df["date"].dt.isocalendar().week

In [365]:
main_df["day"] = main_df["date"].dt.day

In [366]:
# add a month variable to the dataset
main_df["month"] = main_df["date"].dt.month

In [367]:
main_df.head()

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour,weekdays,week,day,month
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-23 03:00:00,3,5,8,26,2
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-23 07:00:00,7,5,8,26,2
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-23 11:00:00,11,5,8,26,2
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-23 15:00:00,15,5,8,26,2
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-23 19:00:00,19,5,8,26,2

In [368]:
main_df.month.unique()

array([2, 3, 4, 5, 6])

In [369]:
main_df.week.unique()

<IntegerArray>
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Length: 15, dtype: UInt32

In [370]:
main_df.day.unique()

array([26, 27, 28,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 29, 30, 31])

In [371]:
main_df.weekdays.unique()

array([5, 6, 0, 1, 2, 3, 4])

In [372]:
main_df.hour.unique()

array([ 3,  7, 11, 15, 19, 23,  1,  5,  9, 12, 13, 17, 21,  8,  0,  4, 16,
       20,  2,  6, 10, 14, 18, 22])

In [373]:
main_df.hour.value_counts()

8     256575
12    255324
16    255044
20    254899
4     254811
0     254270
5     167241
9     166829
21    166658
13    166555
17    166351
1     164441
7      51882
15     50810
11     50739
23     50668
19     50589
3      50192
6      20032
22     19912
14     19706
10     19500
18     19485
2      18883
Name: hour, dtype: int64

In [374]:
main_df.interval.unique()

array(['REGULAR', 'RECOVR AUD'], dtype=object)

In [375]:
# def my_recode(x):
#    if (x == 5 or x == 6) :
#        return 1
#    else:
#        return 0
    
#main_df['weekends'] = main_df['weekdays'].apply(my_recode)
#main_df.head(40)

In [376]:
main_df['weekend'] = (main_df.weekdays == 5) |  (main_df.weekdays == 6)
main_df.head(40)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,exit,time_clone,hour,weekdays,week,day,month,weekend
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,2671257,2022-12-23 03:00:00,3,5,8,26,2,True
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,2671278,2022-12-23 07:00:00,7,5,8,26,2,True
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,2671380,2022-12-23 11:00:00,11,5,8,26,2,True
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,2671465,2022-12-23 15:00:00,15,5,8,26,2,True
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,2671530,2022-12-23 19:00:00,19,5,8,26,2,True
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,7689890,2671568,2022-12-23 23:00:00,23,5,8,26,2,True
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,7689903,2671580,2022-12-23 03:00:00,3,6,8,27,2,True
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,7689908,2671583,2022-12-23 07:00:00,7,6,8,27,2,True
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,11:00:00,REGULAR,7689924,2671637,2022-12-23 11:00:00,11,6,8,27,2,True
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,15:00:00,REGULAR,7689970,2671692,2022-12-23 15:00:00,15,6,8,27,2,True
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,19:00:00,REGULAR,7690010,2671742,2022-12-23 19:00:00,19,6,8,27,2,True
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,23:00:00,REGULAR,7690046,2671763,2022-12-23 23:00:00,23,6,8,27,2,True
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,03:00:00,REGULAR,7690057,2671766,2022-12-23 03:00:00,3,0,9,28,2,False
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,07:00:00,REGULAR,7690058,2671821,2022-12-23 07:00:00,7,0,9,28,2,False
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,11:00:00,REGULAR,7690091,2672117,2022-12-23 11:00:00,11,0,9,28,2,False
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,15:00:00,REGULAR,7690159,2672193,2022-12-23 15:00:00,15,0,9,28,2,False
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,19:00:00,REGULAR,7690336,2672264,2022-12-23 19:00:00,19,0,9,28,2,False
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,23:00:00,REGULAR,7690377,2672288,2022-12-23 23:00:00,23,0,9,28,2,False
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,03:00:00,REGULAR,7690386,2672291,2022-12-23 03:00:00,3,1,9,1,3,False
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,07:00:00,REGULAR,7690388,2672343,2022-12-23 07:00:00,7,1,9,1,3,False
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,11:00:00,REGULAR,7690420,2672647,2022-12-23 11:00:00,11,1,9,1,3,False
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,15:00:00,REGULAR,7690497,2672714,2022-12-23 15:00:00,15,1,9,1,3,False
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,19:00:00,REGULAR,7690681,2672803,2022-12-23 19:00:00,19,1,9,1,3,False
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,23:00:00,REGULAR,7690719,2672824,2022-12-23 23:00:00,23,1,9,1,3,False
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,03:00:00,REGULAR,7690725,2672830,2022-12-23 03:00:00,3,2,9,2,3,False
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,07:00:00,REGULAR,7690730,2672886,2022-12-23 07:00:00,7,2,9,2,3,False
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,11:00:00,REGULAR,7690764,2673196,2022-12-23 11:00:00,11,2,9,2,3,False
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,15:00:00,REGULAR,7690834,2673275,2022-12-23 15:00:00,15,2,9,2,3,False
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,19:00:00,REGULAR,7691026,2673349,2022-12-23 19:00:00,19,2,9,2,3,False
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,23:00:00,REGULAR,7691071,2673379,2022-12-23 23:00:00,23,2,9,2,3,False
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,03:00:00,REGULAR,7691078,2673386,2022-12-23 03:00:00,3,3,9,3,3,False
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,07:00:00,REGULAR,7691083,2673435,2022-12-23 07:00:00,7,3,9,3,3,False
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,11:00:00,REGULAR,7691111,2673707,2022-12-23 11:00:00,11,3,9,3,3,False
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,15:00:00,REGULAR,7691171,2673791,2022-12-23 15:00:00,15,3,9,3,3,False
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,19:00:00,REGULAR,7691319,2673892,2022-12-23 19:00:00,19,3,9,3,3,False
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,23:00:00,REGULAR,7691363,2673919,2022-12-23 23:00:00,23,3,9,3,3,False
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,03:00:00,REGULAR,7691372,2673927,2022-12-23 03:00:00,3,4,9,4,3,False
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,07:00:00,REGULAR,7691374,2673965,2022-12-23 07:00:00,7,4,9,4,3,False
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,11:00:00,REGULAR,7691399,2674256,2022-12-23 11:00:00,11,4,9,4,3,False
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,15:00:00,REGULAR,7691470,2674324,2022-12-23 15:00:00,15,4,9,4,3,False

In [377]:
# main_df.drop(['weekends'], axis=1)

In [379]:
min_max_df=main_df.groupby(['station', 'station_id', 'control_area','device_position','line','division','date']).agg(hour_min=('hour','min'),hour_max=('hour','max'), entry_min=('entry','min'), entry_max=('entry', 'max'), exit_min=('exit', 'min'), exit_max=('exit','max')).reset_index()

In [381]:
min_max_df.head(40)

,station,station_id,control_area,device_position,line,division,date,hour_min,hour_max,entry_min,entry_max,exit_min,exit_max
0,1 AV,R248,H007,00-00-00,L,BMT,2022-02-26,3,23,15727954,15727954,18465387,18465388
1,1 AV,R248,H007,00-00-00,L,BMT,2022-02-27,3,23,15727954,15727954,18465388,18465393
2,1 AV,R248,H007,00-00-00,L,BMT,2022-02-28,3,23,15727954,15728695,18465393,18467923
3,1 AV,R248,H007,00-00-00,L,BMT,2022-03-01,3,23,15728706,15729440,18467996,18470794
4,1 AV,R248,H007,00-00-00,L,BMT,2022-03-02,3,23,15729463,15730194,18470883,18473712
5,1 AV,R248,H007,00-00-00,L,BMT,2022-03-03,3,23,15730215,15731024,18473795,18476653
6,1 AV,R248,H007,00-00-00,L,BMT,2022-03-04,3,23,15731042,15731762,18476745,18479791
7,1 AV,R248,H007,00-00-00,L,BMT,2022-03-05,3,23,15731799,15732150,18479989,18482026
8,1 AV,R248,H007,00-00-00,L,BMT,2022-03-06,3,23,15732178,15732429,18482244,18483816
9,1 AV,R248,H007,00-00-00,L,BMT,2022-03-07,3,23,15732438,15733100,18483881,18486696
10,1 AV,R248,H007,00-00-00,L,BMT,2022-03-08,3,23,15733108,15733841,18486757,18489587
11,1 AV,R248,H007,00-00-00,L,BMT,2022-03-09,3,23,15733854,15734683,18489656,18492356
12,1 AV,R248,H007,00-00-00,L,BMT,2022-03-10,3,23,15734702,15735497,18492434,18495343
13,1 AV,R248,H007,00-00-00,L,BMT,2022-03-11,3,23,15735522,15736315,18495427,18498366
14,1 AV,R248,H007,00-00-00,L,BMT,2022-03-12,3,23,15736354,15736694,18498584,18500387
15,1 AV,R248,H007,00-00-00,L,BMT,2022-03-13,4,20,15736717,15736935,18500550,18502091
16,1 AV,R248,H007,00-00-00,L,BMT,2022-03-14,0,20,15736999,15737660,18502330,18504824
17,1 AV,R248,H007,00-00-00,L,BMT,2022-03-15,0,20,15737730,15738377,18505037,18507629
18,1 AV,R248,H007,00-00-00,L,BMT,2022-03-16,0,20,15738456,15739199,18507946,18510646
19,1 AV,R248,H007,00-00-00,L,BMT,2022-03-17,0,20,15739279,15739976,18510909,18513733
20,1 AV,R248,H007,00-00-00,L,BMT,2022-03-18,0,20,15740078,15740715,18514088,18516696
21,1 AV,R248,H007,00-00-00,L,BMT,2022-03-19,0,20,15740820,15741083,18517169,18519225
22,1 AV,R248,H007,00-00-00,L,BMT,2022-03-20,0,20,15741173,15741437,18519643,18521289
23,1 AV,R248,H007,00-00-00,L,BMT,2022-03-21,0,20,15741486,15742071,18521532,18524075
24,1 AV,R248,H007,00-00-00,L,BMT,2022-03-22,0,20,15742137,15742833,18524314,18526947
25,1 AV,R248,H007,00-00-00,L,BMT,2022-03-23,0,20,15742902,15743508,18527215,18529681
26,1 AV,R248,H007,00-00-00,L,BMT,2022-03-24,0,20,15743584,15744289,18529945,18532431
27,1 AV,R248,H007,00-00-00,L,BMT,2022-03-25,0,20,15744384,15745073,18532719,18535553
28,1 AV,R248,H007,00-00-00,L,BMT,2022-03-26,0,20,15745180,15745511,18536010,18537839
29,1 AV,R248,H007,00-00-00,L,BMT,2022-03-27,0,20,15745641,15745909,18538247,18539787
30,1 AV,R248,H007,00-00-00,L,BMT,2022-03-28,0,20,15745985,15746662,18539987,18542438
31,1 AV,R248,H007,00-00-00,L,BMT,2022-03-29,0,20,15746733,15747458,18542639,18545248
32,1 AV,R248,H007,00-00-00,L,BMT,2022-03-30,0,20,15747543,15748245,18545490,18548104
33,1 AV,R248,H007,00-00-00,L,BMT,2022-03-31,0,20,15748322,15748848,18548384,18551022
34,1 AV,R248,H007,00-00-00,L,BMT,2022-04-01,0,20,15748943,15749626,18551347,18553971
35,1 AV,R248,H007,00-00-00,L,BMT,2022-04-02,0,20,15749731,15750042,18554406,18556457
36,1 AV,R248,H007,00-00-00,L,BMT,2022-04-03,0,20,15750131,15750361,18556862,18558445
37,1 AV,R248,H007,00-00-00,L,BMT,2022-04-04,0,20,15750420,15751046,18558680,18561415
38,1 AV,R248,H007,00-00-00,L,BMT,2022-04-05,0,20,15751126,15751810,18561680,18564305
39,1 AV,R248,H007,00-00-00,L,BMT,2022-04-06,0,20,15751899,15752602,18564566,18567167

In [382]:
min_max_df.columns

Index(['station', 'station_id', 'control_area', 'device_position', 'line',
       'division', 'date', 'hour_min', 'hour_max', 'entry_min', 'entry_max',
       'exit_min', 'exit_max'],
      dtype='object')

In [383]:
merged_df=pd.merge(main_df,min_max_df, on=['station', 'station_id', 'control_area','device_position','line','division','date'], how='left')

In [385]:
merged_df.tail(50)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,...,week,day,month,weekend,hour_min,hour_max,entry_min,entry_max,exit_min,exit_max
2951346,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-02,17:00:00,REGULAR,333423,...,22,2,6,False,1,21,333353,333429,0,0
2951347,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-02,21:00:00,REGULAR,333429,...,22,2,6,False,1,21,333353,333429,0,0
2951348,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,01:00:00,REGULAR,333432,...,22,3,6,False,1,21,333432,333517,0,0
2951349,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,05:00:00,REGULAR,333432,...,22,3,6,False,1,21,333432,333517,0,0
2951350,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,09:00:00,REGULAR,333453,...,22,3,6,False,1,21,333432,333517,0,0
2951351,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,13:00:00,REGULAR,333475,...,22,3,6,False,1,21,333432,333517,0,0
2951352,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,17:00:00,REGULAR,333504,...,22,3,6,False,1,21,333432,333517,0,0
2951353,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,2022-06-03,21:00:00,REGULAR,333517,...,22,3,6,False,1,21,333432,333517,0,0
2951354,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,01:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951355,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,05:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951356,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,09:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951357,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,13:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951358,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,17:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951359,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-28,21:00:00,REGULAR,0,...,21,28,5,True,1,21,0,0,389,395
2951360,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,01:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951361,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,05:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951362,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,09:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951363,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,13:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951364,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,17:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951365,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-29,21:00:00,REGULAR,0,...,21,29,5,True,1,21,0,0,395,405
2951366,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,01:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951367,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,05:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951368,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,09:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951369,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,13:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951370,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,17:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951371,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-30,21:00:00,REGULAR,0,...,22,30,5,False,1,21,0,0,405,423
2951372,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,01:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951373,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,05:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951374,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,09:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951375,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,13:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951376,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,17:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951377,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-05-31,21:00:00,REGULAR,0,...,22,31,5,False,1,21,0,0,425,426
2951378,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,01:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951379,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,05:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951380,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,09:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951381,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,13:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951382,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,17:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951383,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-01,21:00:00,REGULAR,0,...,22,1,6,False,1,21,0,0,426,430
2951384,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,01:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951385,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,05:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951386,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,09:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951387,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,13:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951388,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,17:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951389,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-02,21:00:00,REGULAR,0,...,22,2,6,False,1,21,0,0,430,432
2951390,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,01:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951391,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,05:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951392,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,09:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951393,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,13:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951394,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,17:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435
2951395,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,2022-06-03,21:00:00,REGULAR,0,...,22,3,6,False,1,21,0,0,433,435

In [386]:
merged_df.columns

Index(['control_area', 'station_id', 'device_position', 'station', 'line',
       'division', 'date', 'time', 'interval', 'entry', 'exit', 'time_clone',
       'hour', 'weekdays', 'week', 'day', 'month', 'weekend', 'hour_min',
       'hour_max', 'entry_min', 'entry_max', 'exit_min', 'exit_max'],
      dtype='object')

In [387]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2951396 entries, 0 to 2951395
Data columns (total 24 columns):
 #   Column           Dtype
---  ------           -----
 0   control_area     object
 1   station_id       object
 2   device_position  object
 3   station          object
 4   line             object
 5   division         object
 6   date             datetime64[ns]
 7   time             object
 8   interval         object
 9   entry            int64
 10  exit             int64
 11  time_clone       datetime64[ns]
 12  hour             int64
 13  weekdays         int64
 14  week             UInt32
 15  day              int64
 16  month            int64
 17  weekend          bool
 18  hour_min         int64
 19  hour_max         int64
 20  entry_min        int64
 21  entry_max        int64
 22  exit_min         int64
 23  exit_max         int64
dtypes: UInt32(1), bool(1), datetime64[ns](2), int64(12), object(8)
memory usage: 534.8+ MB

In [388]:
# rename columns and keep the changes
merged_df['min_hour_key'] =(merged_df.hour == merged_df.hour_min)
merged_df['max_hour_key'] =(merged_df.hour == merged_df.hour_max)
merged_df['min_entry_key'] =(merged_df.entry == merged_df.entry_min)
merged_df['max_entry_key'] =(merged_df.entry == merged_df.entry_max)
merged_df['min_exit_key'] =(merged_df.exit == merged_df.exit_min)
merged_df['max_exit_key'] =(merged_df.exit == merged_df.exit_max)

In [389]:
merged_df.head(20)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,...,entry_min,entry_max,exit_min,exit_max,min_hour_key,max_hour_key,min_entry_key,max_entry_key,min_exit_key,max_exit_key
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,...,7689737,7689890,2671257,2671568,True,False,True,False,True,False
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,...,7689737,7689890,2671257,2671568,False,False,False,False,False,False
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,...,7689737,7689890,2671257,2671568,False,False,False,False,False,False
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,...,7689737,7689890,2671257,2671568,False,False,False,False,False,False
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,...,7689737,7689890,2671257,2671568,False,False,False,False,False,False
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,7689890,...,7689737,7689890,2671257,2671568,False,True,False,True,False,True
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,7689903,...,7689903,7690046,2671580,2671763,True,False,True,False,True,False
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,7689908,...,7689903,7690046,2671580,2671763,False,False,False,False,False,False
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,11:00:00,REGULAR,7689924,...,7689903,7690046,2671580,2671763,False,False,False,False,False,False
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,15:00:00,REGULAR,7689970,...,7689903,7690046,2671580,2671763,False,False,False,False,False,False
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,19:00:00,REGULAR,7690010,...,7689903,7690046,2671580,2671763,False,False,False,False,False,False
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,23:00:00,REGULAR,7690046,...,7689903,7690046,2671580,2671763,False,True,False,True,False,True
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,03:00:00,REGULAR,7690057,...,7690057,7690377,2671766,2672288,True,False,True,False,True,False
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,07:00:00,REGULAR,7690058,...,7690057,7690377,2671766,2672288,False,False,False,False,False,False
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,11:00:00,REGULAR,7690091,...,7690057,7690377,2671766,2672288,False,False,False,False,False,False
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,15:00:00,REGULAR,7690159,...,7690057,7690377,2671766,2672288,False,False,False,False,False,False
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,19:00:00,REGULAR,7690336,...,7690057,7690377,2671766,2672288,False,False,False,False,False,False
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,23:00:00,REGULAR,7690377,...,7690057,7690377,2671766,2672288,False,True,False,True,False,True
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,03:00:00,REGULAR,7690386,...,7690386,7690719,2672291,2672824,True,False,True,False,True,False
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,07:00:00,REGULAR,7690388,...,7690386,7690719,2672291,2672824,False,False,False,False,False,False

In [391]:
merged_df['pls_min_exit'] =(merged_df.min_hour_key == merged_df.min_exit_key)
merged_df['pls_max_exit'] =(merged_df.max_hour_key == merged_df.max_exit_key)
merged_df['pls_min_entry'] =(merged_df.min_hour_key == merged_df.min_entry_key)
merged_df['pls_max_entry'] =(merged_df.max_hour_key == merged_df.max_entry_key)

In [393]:
cross_check_df=merged_df.groupby(['station', 'station_id', 'control_area','device_position','line','division','date']).agg(plausible_min_exit=('pls_min_exit','min'),plausible_max_exit=('pls_max_exit','min'),plausible_min_entry=('pls_min_entry','min'),plausible_max_entry=('pls_max_entry','min')).reset_index()

In [394]:
cross_check_df.head(20)

,station,station_id,control_area,device_position,line,division,date,plausible_min_exit,plausible_max_exit,plausible_min_entry,plausible_max_entry
0,1 AV,R248,H007,00-00-00,L,BMT,2022-02-26,False,False,False,False
1,1 AV,R248,H007,00-00-00,L,BMT,2022-02-27,True,False,False,False
2,1 AV,R248,H007,00-00-00,L,BMT,2022-02-28,True,True,True,True
3,1 AV,R248,H007,00-00-00,L,BMT,2022-03-01,True,True,True,True
4,1 AV,R248,H007,00-00-00,L,BMT,2022-03-02,True,True,True,True
5,1 AV,R248,H007,00-00-00,L,BMT,2022-03-03,True,True,True,True
6,1 AV,R248,H007,00-00-00,L,BMT,2022-03-04,True,True,True,True
7,1 AV,R248,H007,00-00-00,L,BMT,2022-03-05,True,True,True,True
8,1 AV,R248,H007,00-00-00,L,BMT,2022-03-06,True,True,True,True
9,1 AV,R248,H007,00-00-00,L,BMT,2022-03-07,True,True,True,True
10,1 AV,R248,H007,00-00-00,L,BMT,2022-03-08,True,True,True,True
11,1 AV,R248,H007,00-00-00,L,BMT,2022-03-09,True,True,True,True
12,1 AV,R248,H007,00-00-00,L,BMT,2022-03-10,True,True,True,True
13,1 AV,R248,H007,00-00-00,L,BMT,2022-03-11,True,True,True,True
14,1 AV,R248,H007,00-00-00,L,BMT,2022-03-12,True,True,True,True
15,1 AV,R248,H007,00-00-00,L,BMT,2022-03-13,True,True,True,True
16,1 AV,R248,H007,00-00-00,L,BMT,2022-03-14,True,True,True,True
17,1 AV,R248,H007,00-00-00,L,BMT,2022-03-15,True,True,True,True
18,1 AV,R248,H007,00-00-00,L,BMT,2022-03-16,True,True,True,True
19,1 AV,R248,H007,00-00-00,L,BMT,2022-03-17,True,True,True,True

In [395]:
merged_df=pd.merge(merged_df,cross_check_df, on=['station', 'station_id', 'control_area','device_position','line','division','date'], how='left')

In [396]:
merged_df.head(40)

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,...,min_exit_key,max_exit_key,pls_min_exit,pls_max_exit,pls_min_entry,pls_max_entry,plausible_min_exit,plausible_max_exit,plausible_min_entry,plausible_max_entry
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,03:00:00,REGULAR,7689737,...,True,False,True,True,True,True,True,True,True,True
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,07:00:00,REGULAR,7689741,...,False,False,True,True,True,True,True,True,True,True
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,11:00:00,REGULAR,7689758,...,False,False,True,True,True,True,True,True,True,True
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,15:00:00,REGULAR,7689791,...,False,False,True,True,True,True,True,True,True,True
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,19:00:00,REGULAR,7689858,...,False,False,True,True,True,True,True,True,True,True
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-26,23:00:00,REGULAR,7689890,...,False,True,True,True,True,True,True,True,True,True
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,03:00:00,REGULAR,7689903,...,True,False,True,True,True,True,True,True,True,True
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,07:00:00,REGULAR,7689908,...,False,False,True,True,True,True,True,True,True,True
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,11:00:00,REGULAR,7689924,...,False,False,True,True,True,True,True,True,True,True
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,15:00:00,REGULAR,7689970,...,False,False,True,True,True,True,True,True,True,True
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,19:00:00,REGULAR,7690010,...,False,False,True,True,True,True,True,True,True,True
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-27,23:00:00,REGULAR,7690046,...,False,True,True,True,True,True,True,True,True,True
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,03:00:00,REGULAR,7690057,...,True,False,True,True,True,True,True,True,True,True
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,07:00:00,REGULAR,7690058,...,False,False,True,True,True,True,True,True,True,True
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,11:00:00,REGULAR,7690091,...,False,False,True,True,True,True,True,True,True,True
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,15:00:00,REGULAR,7690159,...,False,False,True,True,True,True,True,True,True,True
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,19:00:00,REGULAR,7690336,...,False,False,True,True,True,True,True,True,True,True
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-02-28,23:00:00,REGULAR,7690377,...,False,True,True,True,True,True,True,True,True,True
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,03:00:00,REGULAR,7690386,...,True,False,True,True,True,True,True,True,True,True
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,07:00:00,REGULAR,7690388,...,False,False,True,True,True,True,True,True,True,True
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,11:00:00,REGULAR,7690420,...,False,False,True,True,True,True,True,True,True,True
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,15:00:00,REGULAR,7690497,...,False,False,True,True,True,True,True,True,True,True
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,19:00:00,REGULAR,7690681,...,False,False,True,True,True,True,True,True,True,True
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-01,23:00:00,REGULAR,7690719,...,False,True,True,True,True,True,True,True,True,True
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,03:00:00,REGULAR,7690725,...,True,False,True,True,True,True,True,True,True,True
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,07:00:00,REGULAR,7690730,...,False,False,True,True,True,True,True,True,True,True
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,11:00:00,REGULAR,7690764,...,False,False,True,True,True,True,True,True,True,True
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,15:00:00,REGULAR,7690834,...,False,False,True,True,True,True,True,True,True,True
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,19:00:00,REGULAR,7691026,...,False,False,True,True,True,True,True,True,True,True
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-02,23:00:00,REGULAR,7691071,...,False,True,True,True,True,True,True,True,True,True
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,03:00:00,REGULAR,7691078,...,True,False,True,True,True,True,True,True,True,True
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,07:00:00,REGULAR,7691083,...,False,False,True,True,True,True,True,True,True,True
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,11:00:00,REGULAR,7691111,...,False,False,True,True,True,True,True,True,True,True
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,15:00:00,REGULAR,7691171,...,False,False,True,True,True,True,True,True,True,True
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,19:00:00,REGULAR,7691319,...,False,False,True,True,True,True,True,True,True,True
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-03,23:00:00,REGULAR,7691363,...,False,True,True,True,True,True,True,True,True,True
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,03:00:00,REGULAR,7691372,...,True,False,True,True,True,True,True,True,True,True
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,07:00:00,REGULAR,7691374,...,False,False,True,True,True,True,True,True,True,True
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,11:00:00,REGULAR,7691399,...,False,False,True,True,True,True,True,True,True,True
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,2022-03-04,15:00:00,REGULAR,7691470,...,False,False,True,True,True,True,True,True,True,True

In [398]:
merged_df['ultimate_crosscheck'] = ((merged_df.plausible_min_exit== True) &  (merged_df.plausible_max_exit == True) & (merged_df.plausible_min_entry == True) & (merged_df.plausible_max_entry == True))

In [399]:
daily_merged = (merged_df.min_hour_key == True) | (merged_df.max_hour_key == True)

In [400]:
daily_merged_df=merged_df[daily_merged]

In [401]:
daily_merged_df.sort_values(['station', 'station_id', 'control_area','device_position','line','division','date'])

,control_area,station_id,device_position,station,line,division,date,time,interval,entry,...,max_exit_key,pls_min_exit,pls_max_exit,pls_min_entry,pls_max_entry,plausible_min_exit,plausible_max_exit,plausible_min_entry,plausible_max_entry,ultimate_crosscheck
32811,H007,R248,00-00-00,1 AV,L,BMT,2022-02-26,03:00:00,REGULAR,15727954,...,False,True,True,True,False,False,False,False,False,False
32816,H007,R248,00-00-00,1 AV,L,BMT,2022-02-26,23:00:00,REGULAR,15727954,...,True,True,True,False,True,False,False,False,False,False
32817,H007,R248,00-00-00,1 AV,L,BMT,2022-02-27,03:00:00,REGULAR,15727954,...,False,True,True,True,False,True,False,False,False,False
32822,H007,R248,00-00-00,1 AV,L,BMT,2022-02-27,23:00:00,REGULAR,15727954,...,True,True,True,False,True,True,False,False,False,False
32823,H007,R248,00-00-00,1 AV,L,BMT,2022-02-28,03:00:00,REGULAR,15727954,...,False,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925754,R419,R326,00-05-01,ZEREGA AV,6,IRT,2022-06-01,21:00:00,REGULAR,39,...,True,False,True,False,True,False,False,False,False,False
2925755,R419,R326,00-05-01,ZEREGA AV,6,IRT,2022-06-02,01:00:00,REGULAR,39,...,True,True,False,True,False,False,False,False,False,False
2925760,R419,R326,00-05-01,ZEREGA AV,6,IRT,2022-06-02,21:00:00,REGULAR,39,...,True,False,True,False,True,False,False,False,False,False
2925761,R419,R326,00-05-01,ZEREGA AV,6,IRT,2022-06-03,01:00:00,REGULAR,39,...,True,True,False,True,False,False,False,False,False,False
2925766,R419,R326,00-05-01,ZEREGA AV,6,IRT,2022-06-03,21:00:00,REGULAR,39,...,True,False,True,False,True,False,False,False,False,False

In [402]:
daily_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 986528 entries, 0 to 2951395
Data columns (total 39 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   control_area         986528 non-null  object
 1   station_id           986528 non-null  object
 2   device_position      986528 non-null  object
 3   station              986528 non-null  object
 4   line                 986528 non-null  object
 5   division             986528 non-null  object
 6   date                 986528 non-null  datetime64[ns]
 7   time                 986528 non-null  object
 8   interval             986528 non-null  object
 9   entry                986528 non-null  int64
 10  exit                 986528 non-null  int64
 11  time_clone           986528 non-null  datetime64[ns]
 12  hour                 986528 non-null  int64
 13  weekdays             986528 non-null  int64
 14  week                 986528 non-null  UInt32
 15  day                  986528 non-null  int64
 16  month                986528 non-null  int64
 17  weekend              986528 non-null  bool
 18  hour_min             986528 non-null  int64
 19  hour_max             986528 non-null  int64
 20  entry_min            986528 non-null  int64
 21  entry_max            986528 non-null  int64
 22  exit_min             986528 non-null  int64
 23  exit_max             986528 non-null  int64
 24  min_hour_key         986528 non-null  bool
 25  max_hour_key         986528 non-null  bool
 26  min_entry_key        986528 non-null  bool
 27  max_entry_key        986528 non-null  bool
 28  min_exit_key         986528 non-null  bool
 29  max_exit_key         986528 non-null  bool
 30  pls_min_exit         986528 non-null  bool
 31  pls_max_exit         986528 non-null  bool
 32  pls_min_entry        986528 non-null  bool
 33  pls_max_entry        986528 non-null  bool
 34  plausible_min_exit   986528 non-null  bool
 35  plausible_max_exit   986528 non-null  bool
 36  plausible_min_entry  986528 non-null  bool
 37  plausible_max_entry  986528 non-null  bool
 38  ultimate_crosscheck  986528 non-null  bool
dtypes: UInt32(1), bool(16), datetime64[ns](2), int64(12), object(8)
memory usage: 192.9+ MB

In [403]:
cleared_master_df=daily_merged_df.groupby(['station', 'station_id', 'control_area','device_position','line','division','date']).agg(time_min=('time','min'),time_max=('time','max'), hour_min=('hour','min'),hour_max=('hour','max'), entry_min=('entry','min'), entry_max=('entry', 'max'), exit_min=('exit', 'min'), exit_max=('exit','max'), cross_check_mean=('ultimate_crosscheck','mean'),cross_check_min=('ultimate_crosscheck','min')).reset_index()
cleared_master_df.tail(40)

,station,station_id,control_area,device_position,line,division,date,time_min,time_max,hour_min,hour_max,entry_min,entry_max,exit_min,exit_max,cross_check_mean,cross_check_min
492378,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-04-25,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492379,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-04-26,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492380,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-04-27,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492381,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-04-28,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492382,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-04-29,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492383,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-04-30,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492384,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-01,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492385,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-02,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492386,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-03,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492387,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-04,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492388,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-05,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492389,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-06,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492390,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-07,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492391,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-08,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492392,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-09,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492393,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-10,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492394,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-11,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492395,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-12,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492396,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-13,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492397,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-14,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492398,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-15,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492399,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-16,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492400,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-17,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492401,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-18,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492402,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-19,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492403,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-20,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492404,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-21,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492405,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-22,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492406,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-23,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492407,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-24,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492408,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-25,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492409,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-26,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492410,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-27,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492411,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-28,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492412,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-29,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492413,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-30,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492414,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-05-31,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492415,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-06-01,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492416,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-06-02,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False
492417,ZEREGA AV,R326,R419,00-05-01,6,IRT,2022-06-03,01:00:00,21:00:00,1,21,39,39,271,271,0.0,False

In [404]:
cleared_master_df['daily_entry'] = cleared_master_df.entry_max- cleared_master_df.entry_min
cleared_master_df['daily_exit'] = cleared_master_df.exit_max- cleared_master_df.exit_min
cleared_master_df['hour_interval'] = cleared_master_df.hour_max - cleared_master_df.hour_min
cleared_master_df['avg_hourly_entry'] = cleared_master_df.daily_entry / cleared_master_df.hour_interval
cleared_master_df['avg_hourly_exit'] = cleared_master_df.daily_exit / cleared_master_df.hour_interval

In [405]:
cleared_master_df.head(40)

,station,station_id,control_area,device_position,line,division,date,time_min,time_max,hour_min,...,entry_max,exit_min,exit_max,cross_check_mean,cross_check_min,daily_entry,daily_exit,hour_interval,avg_hourly_entry,avg_hourly_exit
0,1 AV,R248,H007,00-00-00,L,BMT,2022-02-26,03:00:00,23:00:00,3,...,15727954,18465387,18465388,0.0,False,0,1,20,0.0,0.1
1,1 AV,R248,H007,00-00-00,L,BMT,2022-02-27,03:00:00,23:00:00,3,...,15727954,18465388,18465393,0.0,False,0,5,20,0.0,0.2
2,1 AV,R248,H007,00-00-00,L,BMT,2022-02-28,03:00:00,23:00:00,3,...,15728695,18465393,18467923,1.0,True,741,2530,20,37.0,126.5
3,1 AV,R248,H007,00-00-00,L,BMT,2022-03-01,03:00:00,23:00:00,3,...,15729440,18467996,18470794,1.0,True,734,2798,20,36.7,139.9
4,1 AV,R248,H007,00-00-00,L,BMT,2022-03-02,03:00:00,23:00:00,3,...,15730194,18470883,18473712,1.0,True,731,2829,20,36.5,141.4
5,1 AV,R248,H007,00-00-00,L,BMT,2022-03-03,03:00:00,23:00:00,3,...,15731024,18473795,18476653,1.0,True,809,2858,20,40.5,142.9
6,1 AV,R248,H007,00-00-00,L,BMT,2022-03-04,03:00:00,23:00:00,3,...,15731762,18476745,18479791,1.0,True,720,3046,20,36.0,152.3
7,1 AV,R248,H007,00-00-00,L,BMT,2022-03-05,03:00:00,23:00:00,3,...,15732150,18479989,18482026,1.0,True,351,2037,20,17.6,101.8
8,1 AV,R248,H007,00-00-00,L,BMT,2022-03-06,03:00:00,23:00:00,3,...,15732429,18482244,18483816,1.0,True,251,1572,20,12.6,78.6
9,1 AV,R248,H007,00-00-00,L,BMT,2022-03-07,03:00:00,23:00:00,3,...,15733100,18483881,18486696,1.0,True,662,2815,20,33.1,140.8
10,1 AV,R248,H007,00-00-00,L,BMT,2022-03-08,03:00:00,23:00:00,3,...,15733841,18486757,18489587,1.0,True,733,2830,20,36.6,141.5
11,1 AV,R248,H007,00-00-00,L,BMT,2022-03-09,03:00:00,23:00:00,3,...,15734683,18489656,18492356,1.0,True,829,2700,20,41.5,135.0
12,1 AV,R248,H007,00-00-00,L,BMT,2022-03-10,03:00:00,23:00:00,3,...,15735497,18492434,18495343,1.0,True,795,2909,20,39.8,145.4
13,1 AV,R248,H007,00-00-00,L,BMT,2022-03-11,03:00:00,23:00:00,3,...,15736315,18495427,18498366,1.0,True,793,2939,20,39.6,146.9
14,1 AV,R248,H007,00-00-00,L,BMT,2022-03-12,03:00:00,23:00:00,3,...,15736694,18498584,18500387,1.0,True,340,1803,20,17.0,90.2
15,1 AV,R248,H007,00-00-00,L,BMT,2022-03-13,04:00:00,20:00:00,4,...,15736935,18500550,18502091,1.0,True,218,1541,16,13.6,96.3
16,1 AV,R248,H007,00-00-00,L,BMT,2022-03-14,00:00:00,20:00:00,0,...,15737660,18502330,18504824,1.0,True,661,2494,20,33.0,124.7
17,1 AV,R248,H007,00-00-00,L,BMT,2022-03-15,00:00:00,20:00:00,0,...,15738377,18505037,18507629,1.0,True,647,2592,20,32.4,129.6
18,1 AV,R248,H007,00-00-00,L,BMT,2022-03-16,00:00:00,20:00:00,0,...,15739199,18507946,18510646,1.0,True,743,2700,20,37.1,135.0
19,1 AV,R248,H007,00-00-00,L,BMT,2022-03-17,00:00:00,20:00:00,0,...,15739976,18510909,18513733,1.0,True,697,2824,20,34.9,141.2
20,1 AV,R248,H007,00-00-00,L,BMT,2022-03-18,00:00:00,20:00:00,0,...,15740715,18514088,18516696,1.0,True,637,2608,20,31.9,130.4
21,1 AV,R248,H007,00-00-00,L,BMT,2022-03-19,00:00:00,20:00:00,0,...,15741083,18517169,18519225,1.0,True,263,2056,20,13.2,102.8
22,1 AV,R248,H007,00-00-00,L,BMT,2022-03-20,00:00:00,20:00:00,0,...,15741437,18519643,18521289,1.0,True,264,1646,20,13.2,82.3
23,1 AV,R248,H007,00-00-00,L,BMT,2022-03-21,00:00:00,20:00:00,0,...,15742071,18521532,18524075,1.0,True,585,2543,20,29.2,127.2
24,1 AV,R248,H007,00-00-00,L,BMT,2022-03-22,00:00:00,20:00:00,0,...,15742833,18524314,18526947,1.0,True,696,2633,20,34.8,131.7
25,1 AV,R248,H007,00-00-00,L,BMT,2022-03-23,00:00:00,20:00:00,0,...,15743508,18527215,18529681,1.0,True,606,2466,20,30.3,123.3
26,1 AV,R248,H007,00-00-00,L,BMT,2022-03-24,00:00:00,20:00:00,0,...,15744289,18529945,18532431,1.0,True,705,2486,20,35.2,124.3
27,1 AV,R248,H007,00-00-00,L,BMT,2022-03-25,00:00:00,20:00:00,0,...,15745073,18532719,18535553,1.0,True,689,2834,20,34.5,141.7
28,1 AV,R248,H007,00-00-00,L,BMT,2022-03-26,00:00:00,20:00:00,0,...,15745511,18536010,18537839,1.0,True,331,1829,20,16.6,91.5
29,1 AV,R248,H007,00-00-00,L,BMT,2022-03-27,00:00:00,20:00:00,0,...,15745909,18538247,18539787,1.0,True,268,1540,20,13.4,77.0
30,1 AV,R248,H007,00-00-00,L,BMT,2022-03-28,00:00:00,20:00:00,0,...,15746662,18539987,18542438,1.0,True,677,2451,20,33.9,122.5
31,1 AV,R248,H007,00-00-00,L,BMT,2022-03-29,00:00:00,20:00:00,0,...,15747458,18542639,18545248,1.0,True,725,2609,20,36.2,130.4
32,1 AV,R248,H007,00-00-00,L,BMT,2022-03-30,00:00:00,20:00:00,0,...,15748245,18545490,18548104,1.0,True,702,2614,20,35.1,130.7
33,1 AV,R248,H007,00-00-00,L,BMT,2022-03-31,00:00:00,20:00:00,0,...,15748848,18548384,18551022,1.0,True,526,2638,20,26.3,131.9
34,1 AV,R248,H007,00-00-00,L,BMT,2022-04-01,00:00:00,20:00:00,0,...,15749626,18551347,18553971,1.0,True,683,2624,20,34.1,131.2
35,1 AV,R248,H007,00-00-00,L,BMT,2022-04-02,00:00:00,20:00:00,0,...,15750042,18554406,18556457,1.0,True,311,2051,20,15.6,102.5
36,1 AV,R248,H007,00-00-00,L,BMT,2022-04-03,00:00:00,20:00:00,0,...,15750361,18556862,18558445,1.0,True,230,1583,20,11.5,79.2
37,1 AV,R248,H007,00-00-00,L,BMT,2022-04-04,00:00:00,20:00:00,0,...,15751046,18558680,18561415,1.0,True,626,2735,20,31.3,136.8
38,1 AV,R248,H007,00-00-00,L,BMT,2022-04-05,00:00:00,20:00:00,0,...,15751810,18561680,18564305,1.0,True,684,2625,20,34.2,131.2
39,1 AV,R248,H007,00-00-00,L,BMT,2022-04-06,00:00:00,20:00:00,0,...,15752602,18564566,18567167,1.0,True,703,2601,20,35.1,130.1

In [406]:
cleared_master_df['limit_in_hour']=1800
cleared_master_df['over_hourly_exit'] = cleared_master_df.avg_hourly_exit > cleared_master_df.limit_in_hour 
cleared_master_df['over_hourly_entry'] = cleared_master_df.avg_hourly_entry > cleared_master_df.limit_in_hour

In [407]:
cleared_master_df.describe()

,hour_min,hour_max,entry_min,entry_max,exit_min,exit_max,cross_check_mean,daily_entry,daily_exit,hour_interval,avg_hourly_entry,avg_hourly_exit,limit_in_hour
count,"492,418.0","492,418.0","492,418.0","492,418.0","492,418.0","492,418.0","492,418.0","492,418.0","492,418.0","492,418.0","492,293.0","492,293.0","492,418.0"
mean,0.8,20.7,"42,792,229.7","42,803,001.6","34,446,182.0","34,460,482.4",0.7,"10,771.9","14,300.5",19.9,inf,inf,"1,800.0"
std,1.0,1.0,"223,209,250.7","223,226,257.4","196,804,030.8","196,854,552.6",0.5,"2,783,451.8","4,390,164.9",0.8,NaN,NaN,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"1,800.0"
25%,0.0,20.0,"243,282.2","244,024.2","131,072.0","131,152.2",0.0,91.0,91.0,20.0,4.5,4.6,"1,800.0"
50%,0.0,20.0,"1,337,651.0","1,338,541.5","877,297.5","878,220.5",1.0,289.0,306.0,20.0,14.5,15.4,"1,800.0"
75%,1.0,21.0,"5,947,299.2","5,948,535.0","3,961,086.8","3,962,400.8",1.0,567.0,681.0,20.0,28.4,34.1,"1,800.0"
max,23.0,23.0,"2,147,318,974.0","2,147,319,334.0","2,122,442,248.0","2,122,443,345.0",1.0,"1,041,558,110.0","2,061,816,028.0",23.0,inf,inf,"1,800.0"

In [417]:
cleared_master_df.loc[cleared_master_df.avg_hourly_entry > 1800].count()

station              119
station_id           119
control_area         119
device_position      119
line                 119
division             119
date                 119
time_min             119
time_max             119
hour_min             119
hour_max             119
entry_min            119
entry_max            119
exit_min             119
exit_max             119
cross_check_mean     119
cross_check_min      119
daily_entry          119
daily_exit           119
hour_interval        119
avg_hourly_entry     119
avg_hourly_exit      119
limit_in_hour        119
over_hourly_exit     119
over_hourly_entry    119
dtype: int64

In [418]:
cleared_master_df.loc[cleared_master_df.avg_hourly_exit > 1800].count()

station              109
station_id           109
control_area         109
device_position      109
line                 109
division             109
date                 109
time_min             109
time_max             109
hour_min             109
hour_max             109
entry_min            109
entry_max            109
exit_min             109
exit_max             109
cross_check_mean     109
cross_check_min      109
daily_entry          109
daily_exit           109
hour_interval        109
avg_hourly_entry     109
avg_hourly_exit      109
limit_in_hour        109
over_hourly_exit     109
over_hourly_entry    109
dtype: int64

// bir device'ın saatlik okuyabileceği maksimum ve minimum değerler belirle. Bu değerlerin dışında kalan gözlemleri implausible olarak flagle bu değerleri winsorize et.

In [ ]:
main_df.to_csv('master_data.csv')

avg_hourly entry ve exit değerlerini kullanarak her bir istasyon için avg entry ve exit değeri oluştur. Bu değeri yaratırken overly reported değerleri dışarıda bırak.